#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signum.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Signum.Entities;
    
    #line 1 "..\..\Signum\Views\PopupOkControl.cshtml"
    using Signum.Entities.Reflection;
    
    #line default
    #line hidden
    using Signum.Utilities;
    using Signum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Signum/Views/PopupOkControl.cshtml")]
    public partial class PopupOkControl : System.Web.Mvc.WebViewPage<TypeContext>
    {
        public PopupOkControl()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Signum\Views\PopupOkControl.cshtml"
   ModifiableEntity modifiable = Model.UntypedValue as ModifiableEntity; 
            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteAttribute("id", Tuple.Create(" id=\"", 135), Tuple.Create("\"", 168)
            
            #line 4 "..\..\Signum\Views\PopupOkControl.cshtml"
, Tuple.Create(Tuple.Create("", 140), Tuple.Create<System.Object, System.Int32>(Model.Compose("panelPopup")
            
            #line default
            #line hidden
, 140), false)
);

WriteLiteral(" class=\"sf-popup-control\"");

WriteLiteral(" data-prefix=\"");

            
            #line 4 "..\..\Signum\Views\PopupOkControl.cshtml"
                                                                        Write(Model.Prefix);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-title=\"");

            
            #line 4 "..\..\Signum\Views\PopupOkControl.cshtml"
                                                                                                      Write(Navigator.Manager.GetTypeTitle(modifiable));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    <h2><span");

WriteLiteral(" class=\"sf-entity-title\"");

WriteLiteral(">");

            
            #line 5 "..\..\Signum\Views\PopupOkControl.cshtml"
                                  Write(ViewBag.Title ?? Model.UntypedValue.TryToString());

            
            #line default
            #line hidden
WriteLiteral("</span></h2>\r\n    <div");

WriteLiteral(" class=\"sf-button-bar\"");

WriteLiteral(">\r\n        <button");

WriteAttribute("id", Tuple.Create(" id=\"", 437), Tuple.Create("\"", 465)
            
            #line 7 "..\..\Signum\Views\PopupOkControl.cshtml"
, Tuple.Create(Tuple.Create("", 442), Tuple.Create<System.Object, System.Int32>(Model.Compose("btnOk")
            
            #line default
            #line hidden
, 442), false)
);

WriteLiteral(" class=\"sf-entity-button sf-ok-button\"");

WriteLiteral(">OK</button>                \r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Signum\Views\PopupOkControl.cshtml"
Write(Html.ValidationSummaryAjax(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteAttribute("id", Tuple.Create(" id=\"", 594), Tuple.Create("\"", 631)
            
            #line 10 "..\..\Signum\Views\PopupOkControl.cshtml"
, Tuple.Create(Tuple.Create("", 599), Tuple.Create<System.Object, System.Int32>(Model.Compose("divMainControl")
            
            #line default
            #line hidden
, 599), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 632), Tuple.Create("\"", 727)
, Tuple.Create(Tuple.Create("", 640), Tuple.Create("sf-main-control", 640), true)
            
            #line 10 "..\..\Signum\Views\PopupOkControl.cshtml"
, Tuple.Create(Tuple.Create("", 655), Tuple.Create<System.Object, System.Int32>(modifiable != null && modifiable.IsGraphModified ? " sf-changed" : ""
            
            #line default
            #line hidden
, 655), false)
);

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Signum\Views\PopupOkControl.cshtml"
        
            
            #line default
            #line hidden
            
            #line 11 "..\..\Signum\Views\PopupOkControl.cshtml"
           Html.RenderPartial(ViewData[ViewDataKeys.PartialViewName].ToString(), Model);
            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
