#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Signum.Entities;
    using Signum.Utilities;
    using Signum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Signum/Views/ValueLineBox.cshtml")]
    public partial class _Signum_Views_ValueLineBox_cshtml : System.Web.Mvc.WebViewPage<Signum.Web.Context>
    {
        public _Signum_Views_ValueLineBox_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Signum\Views\ValueLineBox.cshtml"
  
    ValueLineBoxOptions options = ViewBag.Options;    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteAttribute("id", Tuple.Create(" id=\"", 96), Tuple.Create("\"", 129)
            
            #line 6 "..\..\Signum\Views\ValueLineBox.cshtml"
, Tuple.Create(Tuple.Create("", 101), Tuple.Create<System.Object, System.Int32>(Model.Compose("panelPopup")
            
            #line default
            #line hidden
, 101), false)
);

WriteLiteral(" class=\"sf-popup-control modal fade sf-value-line-box\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"XXXX\"");

WriteLiteral(" data-prefix=\"");

            
            #line 6 "..\..\Signum\Views\ValueLineBox.cshtml"
                                                                                                                                                        Write(Model.Prefix);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog modal-sm\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close sf-close-button\"");

WriteLiteral(">×</button>\r\n                <h4>");

            
            #line 11 "..\..\Signum\Views\ValueLineBox.cshtml"
               Write(options.title);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <p>\r\n");

WriteLiteral("                    ");

            
            #line 16 "..\..\Signum\Views\ValueLineBox.cshtml"
               Write(options.message);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </p>\r\n");

WriteLiteral("                ");

            
            #line 18 "..\..\Signum\Views\ValueLineBox.cshtml"
           Write(Html.ValueLine(new ValueLine(@ViewBag.type, options.value, Model, "value", null)
                {
                    LabelText = options.labelText,
                    FormGroupStyle = options.labelText.HasText() ? FormGroupStyle.Basic : FormGroupStyle.None,
                    Format = options.format,
                    UnitText = options.unit,
                }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                <button");

WriteAttribute("id", Tuple.Create(" id=\"", 1123), Tuple.Create("\"", 1151)
            
            #line 27 "..\..\Signum\Views\ValueLineBox.cshtml"
, Tuple.Create(Tuple.Create("", 1128), Tuple.Create<System.Object, System.Int32>(Model.Compose("btnOk")
            
            #line default
            #line hidden
, 1128), false)
);

WriteLiteral(" class=\"btn btn-primary sf-entity-button sf-close-button sf-ok-button\"");

WriteLiteral(">");

            
            #line 27 "..\..\Signum\Views\ValueLineBox.cshtml"
                                                                                                                      Write(JavascriptMessage.ok.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
