#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    
    #line 1 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
    using System.Collections.Concurrent;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    
    #line 4 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 2 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 7 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
    using Signum.Engine.Translation;
    
    #line default
    #line hidden
    using Signum.Entities;
    
    #line 6 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
    using Signum.Entities.Authorization;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
    using Signum.Entities.Translation;
    
    #line default
    #line hidden
    using Signum.Utilities;
    using Signum.Web;
    
    #line 3 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
    using Signum.Web.Translation.Controllers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Translation/Views/LocalizableTypeUsedNotLocalized.cshtml")]
    public partial class _Translation_Views_LocalizableTypeUsedNotLocalized_cshtml : System.Web.Mvc.WebViewPage<TranslationOccurrences>
    {
        public _Translation_Views_LocalizableTypeUsedNotLocalized_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
  
    ViewBag.Title = TranslationMessage.CodeTranslations.NiceToString();

    Lite<RoleEntity> selectedRole = ViewBag.Role;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 15 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
Write(Html.ScriptCss("~/Translation/Content/Translation.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 17 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
 if (Model == null)
{

            
            #line default
            #line hidden
WriteLiteral("    <h2>");

            
            #line 19 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
   Write(TranslationMessage.NothingToTranslate.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 20 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <h2>");

            
            #line 23 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 24 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <div");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" onclick=\"document.getElementById(\'myDropdown\').classList.toggle(\'show\');\"");

WriteLiteral(" class=\"dropbtn\"");

WriteLiteral(">\r\n");

            
            #line 28 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                
            
            #line default
            #line hidden
            
            #line 28 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                 if (selectedRole == null)
                {
            
            #line default
            #line hidden
            
            #line 29 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
            Write(TranslationMessage.All.NiceToString());

            
            #line default
            #line hidden
            
            #line 29 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                                                        }
                else
                { 
            
            #line default
            #line hidden
            
            #line 31 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
             Write(selectedRole.ToString());

            
            #line default
            #line hidden
            
            #line 31 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                                           }

            
            #line default
            #line hidden
WriteLiteral("            </button>\r\n            <div");

WriteLiteral(" id=\"myDropdown\"");

WriteLiteral(" class=\"dropdown-content\"");

WriteLiteral(">\r\n");

            
            #line 34 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                
            
            #line default
            #line hidden
            
            #line 34 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                 foreach (var role in Model.LocalizableTypeUsedNotLocalized.Keys)
                {
                    
            
            #line default
            #line hidden
            
            #line 36 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
               Write(Html.ActionLink(role.ToString(), (TranslationController tc) => tc.LocalizableTypeUsedNotLocalized(role)));

            
            #line default
            #line hidden
            
            #line 36 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                                                                                                                             
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 41 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"



            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"st\"");

WriteLiteral(">\r\n\r\n        <tr>\r\n            <th>Role </th>\r\n            <th>Culture Info </th>" +
"\r\n\r\n            <th>Type</th>\r\n            <th>Type Occurrences</th>\r\n          " +
"  <th>Member Info</th>\r\n            <th>Member Occurrences</th>\r\n        </tr>\r\n" +
"\r\n");

            
            #line 55 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
        
            
            #line default
            #line hidden
            
            #line 55 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
         foreach (var reDict in Model.LocalizableTypeUsedNotLocalized)
        {
            foreach (var ci in reDict.Value)
            {
                foreach (var ty in ci.Value)
                {
                    foreach (var m in ty.Value.DictMi)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>");

            
            #line 64 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                           Write(reDict.Key.ToString());

            
            #line default
            #line hidden
WriteLiteral(" </td>\r\n                            <td>");

            
            #line 65 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                           Write(ci.Key.ToString());

            
            #line default
            #line hidden
WriteLiteral(" </td>\r\n                            <td>");

            
            #line 66 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                           Write(ty.Key.ToString());

            
            #line default
            #line hidden
WriteLiteral(" </td>\r\n                            \r\n                            <td>");

            
            #line 68 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                           Write(ty.Value.Ocurrences);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 69 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                           Write(m.Key.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 70 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                           Write(m.Value.ToString());

            
            #line default
            #line hidden
WriteLiteral(" </td>\r\n                        </tr>\r\n");

            
            #line 72 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
                    }
                }
            }
        }

            
            #line default
            #line hidden
WriteLiteral("    </table>\r\n");

            
            #line 77 "..\..\Translation\Views\LocalizableTypeUsedNotLocalized.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
