'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Framework.Procesos.ProcesosAD.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE VIEW    vwEjecutorClientexNombreCliente as SELECT     dbo.tlEjecutoresDeClienteDN.ID, dbo.tlClientedeFachadaDN.Nombre, dbo.tlEjecutoresDeClienteDN.Baja
        '''FROM         dbo.tlEjecutoresDeClienteDN INNER JOIN
        '''                      dbo.tlClientedeFachadaDN ON dbo.tlEjecutoresDeClienteDN.idClientedeFachada = dbo.tlClientedeFachadaDN.ID.
        '''</summary>
        Friend ReadOnly Property vwEjecutorClientexNombreCliente() As String
            Get
                Return ResourceManager.GetString("vwEjecutorClientexNombreCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to create view vwEjecutoresCleintexVmxVc as SELECT     dbo.tlVcEjecutorDeVerboEnClienteDN.ID AS idVEj, dbo.tlVerboDN.ID AS idv, dbo.tlVerboDN.Nombre, dbo.tlVinculoMetodoDN.ID AS idvm, 
        '''                      dbo.tlVinculoMetodoDN.NombreMetodo, dbo.tlVinculoClaseDN.ID AS idvc, dbo.tlVinculoClaseDN.NombreClase
        '''FROM         dbo.tlVcEjecutorDeVerboEnClienteDN INNER JOIN
        '''                      dbo.tlVerboDN ON dbo.tlVcEjecutorDeVerboEnClienteDN.idVerbo = dbo.tlVerboDN.ID INNER JOIN
        '''                      dbo.tlVin [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vwEjecutoresCleintexVmxVc() As String
            Get
                Return ResourceManager.GetString("vwEjecutoresCleintexVmxVc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE VIEW    vwOperacionesRealizadasActivas as SELECT     dbo.tlOperacionRealizadaDN.ID AS idOperacionRealizadaDestino, dbo.vwTransicionesxTipoDN.NombreClaseOrigen, 
        '''                      dbo.vwTransicionesxTipoDN.TipoTransicion, dbo.tlOperacionRealizadaDN.Baja, dbo.tlHEDN.IdEntidadReferida, dbo.tlOperacionDN.Nombre, 
        '''                      dbo.tlHEDN.GUIDReferida
        '''FROM         dbo.tlTransicionRealizadaDN INNER JOIN
        '''                      dbo.vwTransicionesxTipoDN INNER JOIN
        '''                      dbo.tl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vwOperacionesRealizadasActivas() As String
            Get
                Return ResourceManager.GetString("vwOperacionesRealizadasActivas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create VIEW   vwProcesosTransicionesOrDes  as   SELECT     dbo.tlTransicionRealizadaDN.ID, dbo.tlOperacionRealizadaDN.ID AS OpoId, dbo.tlOperacionDN.Nombre AS OpoNOmbre, 
        '''                      dbo.tlOperacionRealizadaDN.Periodo_FInicio AS OpoFI, dbo.tlOperacionRealizadaDN.Periodo_FFinal AS OpoFF, 
        '''                      tlOperacionRealizadaDN_1.ID AS OpdID, tlOperacionDN_1.Nombre AS OpdNombre, tlOperacionRealizadaDN_1.Periodo_FInicio AS OpdFI, 
        '''                      tlOperacionRealizadaDN_1.Periodo_FFinal [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vwProcesosTransicionesOrDes() As String
            Get
                Return ResourceManager.GetString("vwProcesosTransicionesOrDes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create View vwProcesosTrOprOrigenOprDestino as   SELECT     dbo.tlTransicionRealizadaDN.ID, dbo.tlOperacionRealizadaDN.RutaSubordinada AS opoRS, 
        '''                      tlOperacionRealizadaDN_1.RutaSubordinada AS opdRS
        '''FROM         dbo.tlOperacionRealizadaDN INNER JOIN
        '''                      dbo.tlTransicionRealizadaDN ON dbo.tlOperacionRealizadaDN.ID = dbo.tlTransicionRealizadaDN.idOperacionRealizadaOrigen INNER JOIN
        '''                      dbo.tlOperacionRealizadaDN AS tlOperacionRealizadaDN_1 ON 
        '''       [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vwProcesosTrOprOrigenOprDestino() As String
            Get
                Return ResourceManager.GetString("vwProcesosTrOprOrigenOprDestino", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE VIEW    vwTransicionesxTipoDN as  SELECT     dbo.tlTransicionDN.ID, dbo.tlTransicionDN.TipoTransicion, dbo.tlTransicionDN.Baja, dbo.tlTransicionDN.idOperacionOrigen, 
        '''                      dbo.tlTransicionDN.idOperacionDestino, dbo.tlOperacionDN.Nombre AS NombreOpOrigen, tlOperacionDN_1.Nombre AS NombreOpDestino, 
        '''                      dbo.tlVinculoClaseDN.NombreClase AS NombreClaseOrigen, tlVinculoClaseDN_1.NombreClase AS NombreClaseDestino
        '''FROM         dbo.tlVinculoClaseDN INNER JOIN
        '''           [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vwTransicionesxTipoDN() As String
            Get
                Return ResourceManager.GetString("vwTransicionesxTipoDN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE VIEW vwUltimasOperacionesSubordinadas as SELECT     dbo.tlHEDN.IdEntidadReferida AS ID, dbo.tlOperacionRealizadaDN.ID AS idOPR, dbo.tlOperacionRealizadaDN.idOperacion, 
        '''                      dbo.tlOperacionRealizadaDN.Periodo_FInicio, dbo.tlOperacionRealizadaDN.Periodo_FFinal, dbo.tlTransicionDN.TipoTransicion, 
        '''                      dbo.tlOperacionDN.ID AS idOperacionPosible, dbo.tlOperacionDN.Nombre, dbo.tlHEDN.GUIDReferida, 
        '''                      dbo.tlHEDN.TipoEntidadReferidaFullName
        '''FROM     [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vwUltimasOperacionesSubordinadas() As String
            Get
                Return ResourceManager.GetString("vwUltimasOperacionesSubordinadas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create view vwUltimasOperacionesTotales as SELECT     ID, idOPR, idOperacion, Periodo_FInicio, Periodo_FFinal, TipoTransicion, idOperacionPosible, Nombre, GUIDReferida, 
        '''                      TipoEntidadReferidaFullName
        '''FROM         vwUltimasOperacionesTRNormal
        '''UNION
        '''SELECT     ID, idOPR, idOperacion, Periodo_FInicio, Periodo_FFinal, TipoTransicion, idOperacionPosible, Nombre, GUIDReferida, 
        '''                      TipoEntidadReferidaFullName
        '''FROM         vwUltimasOperacionesSubordinadas.
        '''</summary>
        Friend ReadOnly Property vwUltimasOperacionesTotales() As String
            Get
                Return ResourceManager.GetString("vwUltimasOperacionesTotales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE VIEW vwUltimasOperacionesTRNormal as SELECT     dbo.tlHEDN.IdEntidadReferida AS ID, dbo.tlOperacionRealizadaDN.ID AS idOPR, dbo.tlOperacionRealizadaDN.idOperacion, 
        '''                      dbo.tlOperacionRealizadaDN.Periodo_FInicio, dbo.tlOperacionRealizadaDN.Periodo_FFinal, dbo.tlTransicionDN.TipoTransicion, 
        '''                      dbo.tlOperacionDN.ID AS idOperacionPosible, dbo.tlOperacionDN.Nombre, dbo.tlHEDN.GUIDReferida, 
        '''                      dbo.tlHEDN.TipoEntidadReferidaFullName
        '''FROM         [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vwUltimasOperacionesTRNormal() As String
            Get
                Return ResourceManager.GetString("vwUltimasOperacionesTRNormal", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
