#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Signum.Entities;
    
    #line 1 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
    using Signum.Entities.Mailing;
    
    #line default
    #line hidden
    using Signum.Utilities;
    using Signum.Web;
    
    #line 2 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
    using Signum.Web.Mailing;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mailing/Views/EmailMasterTemplate.cshtml")]
    public partial class _Mailing_Views_EmailMasterTemplate_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Mailing_Views_EmailMasterTemplate_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
Write(Html.ScriptCss("~/Mailing/Content/Mailing.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 5 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
 using (var ec = Html.TypeContext<EmailMasterTemplateEntity>())
{
    
            
            #line default
            #line hidden
            
            #line 7 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
Write(Html.ValueLine(ec, e => e.Name));

            
            #line default
            #line hidden
            
            #line 7 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
                                    

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"clearall\"");

WriteLiteral("></div>\r\n");

            
            #line 9 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
Write(Html.EntityTabRepeater(ec, e => e.Messages, er =>
        {
            er.PreserveViewData = true;
        }));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
          
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
