#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signum.Web.Extensions.Mailing.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Signum.Entities;
    
    #line 1 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
    using Signum.Entities.Mailing;
    
    #line default
    #line hidden
    using Signum.Utilities;
    using Signum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mailing/Views/EmailMasterTemplate.cshtml")]
    public partial class EmailMasterTemplate : System.Web.Mvc.WebViewPage<dynamic>
    {
        public EmailMasterTemplate()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
 using (var ec = Html.TypeContext<EmailMasterTemplateDN>())
{
    
            
            #line default
            #line hidden
            
            #line 4 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
Write(Html.ValueLine(ec, e => e.Name));

            
            #line default
            #line hidden
            
            #line 4 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
                                    
    
            
            #line default
            #line hidden
            
            #line 5 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
Write(Html.ValueLine(ec, e => e.State));

            
            #line default
            #line hidden
            
            #line 5 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
                                     


            
            #line default
            #line hidden
WriteLiteral("    <div id=\"messageEditContent\">\r\n        ");


            
            #line 8 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
   Write(Html.ValueLine(ec, e => e.Text, vl =>
               {
                   vl.ValueLineType = ValueLineType.TextArea;
                   vl.ValueHtmlProps["cols"] = "30";
                   vl.ValueHtmlProps["rows"] = "6";
                   vl.ValueHtmlProps["class"] = "sf-email-htmlwrite";
               }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <br />\r\n        <input type=\"button\" class=\"sf-button\" id=\"insertMaster" +
"TemplateTokenButton\" value=\"");


            
            #line 16 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
                                                                                       Write(EmailTemplateViewMessage.InsertMessageContent.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        <input type=\"button\" class=\"sf-button\" id=\"messagePreviewContentBut" +
"ton\" value=\"");


            
            #line 17 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
                                                                                   Write(EmailTemplateViewMessage.PreviewContent.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    </div>\r\n");



WriteLiteral(@"    <div id=""messagePreviewContent"">
        <fieldset>
            <legend>Message</legend>
            <iframe id=""messageBodyContentPreview"" name=""frameNewImage"" src=""about:blank"" class=""sf-email-htmlbody""
                frameborder=""0""></iframe>
            <br />
            <input type=""button"" class=""sf-button"" id=""messageEditContentButton"" value=""");


            
            #line 25 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
                                                                                    Write(EmailTemplateViewMessage.EditContent.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        </fieldset>\r\n    </div>\r\n");


            
            #line 28 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
}

            
            #line default
            #line hidden

            
            #line 29 "..\..\Mailing\Views\EmailMasterTemplate.cshtml"
Write(Html.ScriptsJs("~/Mailing/Scripts/SF_Mail.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
