#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signum.Web.Extensions.Mailing.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Mailing\Views\EmailTemplateMessage.cshtml"
    using Signum.Engine.Translation;
    
    #line default
    #line hidden
    using Signum.Entities;
    
    #line 1 "..\..\Mailing\Views\EmailTemplateMessage.cshtml"
    using Signum.Entities.Mailing;
    
    #line default
    #line hidden
    using Signum.Utilities;
    using Signum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mailing/Views/EmailTemplateMessage.cshtml")]
    public partial class EmailTemplateMessage : System.Web.Mvc.WebViewPage<dynamic>
    {
        public EmailTemplateMessage()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Mailing\Views\EmailTemplateMessage.cshtml"
 using (var ec = Html.TypeContext<EmailTemplateMessageDN>())
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"sf-email-messageContainer\">\r\n        <input type=\"hidden\" class=\"" +
"sf-email-culture\" value=\"");


            
            #line 6 "..\..\Mailing\Views\EmailTemplateMessage.cshtml"
                                                         Write(ec.Value.CultureInfo.CultureInfo.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        ");


            
            #line 7 "..\..\Mailing\Views\EmailTemplateMessage.cshtml"
   Write(Html.ValueLine(ec, e => e.CultureInfo, vl =>
        {
            vl.ValueLineType = ValueLineType.Combo;
            vl.EnumComboItems = CultureInfoLogic.ApplicationCultures.OrderBy(
                ci => ci.Name).ThenBy(ci => ci.IsNeutralCulture).Select(ci =>
                    new SelectListItem 
                    { 
                        Text = ci.DisplayName, 
                        Value = ci.Name, 
                        Selected = ci.Name == ec.Value.CultureInfo.CultureInfo.Name 
                    }).ToList();           
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <fieldset>\r\n            <legend>Replacement</legend>\r\n            <text" +
"area cols=\"30\" rows=\"6\"></textarea>\r\n\r\n        </fieldset>\r\n        ");


            
            #line 24 "..\..\Mailing\Views\EmailTemplateMessage.cshtml"
   Write(Html.ValueLine(ec, e => e.Subject));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"sf-email-messageEditContent\">\r\n            ");


            
            #line 26 "..\..\Mailing\Views\EmailTemplateMessage.cshtml"
       Write(Html.ValueLine(ec, e => e.Text, vl =>
            {
                vl.ValueLineType = ValueLineType.TextArea;
                vl.ValueHtmlProps["cols"] = "30";
                vl.ValueHtmlProps["rows"] = "6";
                vl.ValueHtmlProps["class"] = "sf-email-htmlwrite";
            }));

            
            #line default
            #line hidden
WriteLiteral(@"
            <br />
            <input type=""button"" class=""sf-button sf-email-messagePreviewContentButton"" value=""Preview"" />
        </div>
        <div class=""sf-email-messagePreviewContent"" style=""display: none;"">
            <fieldset>
                <legend>Message</legend>
                <iframe name=""frameNewImage"" src=""about:blank"" class=""sf-email-htmlBody"" frameborder=""0""></iframe>
                <br />
                <input type=""button"" class=""sf-button sf-email-messageEditContentButton"" value=""Edit"" />
            </fieldset>
        </div>
    </div>
");


            
            #line 45 "..\..\Mailing\Views\EmailTemplateMessage.cshtml"
}

            
            #line default
            #line hidden

            
            #line 46 "..\..\Mailing\Views\EmailTemplateMessage.cshtml"
Write(Html.ScriptsJs("~/Mailing/Scripts/SF_Mail.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
