#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Signum.Entities;
    
    #line 1 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
    using Signum.Entities.Mailing;
    
    #line default
    #line hidden
    using Signum.Utilities;
    using Signum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mailing/Views/SmtpNetworkDelivery.cshtml")]
    public partial class _Mailing_Views_SmtpNetworkDelivery_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Mailing_Views_SmtpNetworkDelivery_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
 using (var sc = Html.TypeContext<SmtpNetworkDeliveryEntity>())
{
    
            
            #line default
            #line hidden
            
            #line 5 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
Write(Html.ValueLine(sc, s => s.Port));

            
            #line default
            #line hidden
            
            #line 5 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
                                    
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
Write(Html.ValueLine(sc, s => s.Host));

            
            #line default
            #line hidden
            
            #line 6 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
                                    
    
            
            #line default
            #line hidden
            
            #line 7 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
Write(Html.ValueLine(sc, s => s.UseDefaultCredentials));

            
            #line default
            #line hidden
            
            #line 7 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
                                                     
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
Write(Html.ValueLine(sc, s => s.Username));

            
            #line default
            #line hidden
            
            #line 8 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
                                        
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
Write(Html.ValueLine(sc, s => s.Password, vl => vl.ValueHtmlProps.Add("type", "password")));

            
            #line default
            #line hidden
            
            #line 9 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
                                                                                         
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
Write(Html.ValueLine(sc, s => s.EnableSSL));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
                                         
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
Write(Html.EntityRepeater(sc, s => s.ClientCertificationFiles));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Mailing\Views\SmtpNetworkDelivery.cshtml"
                                                             
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
