//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using Signum.Utilities;
    using Signum.Entities;
    using Signum.Entities.Authorization;
    using Signum.Web;
    using Signum.Web.Auth;
    using Signum.Web.Extensions.Properties;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Auth/Views/ChangePassword.cshtml")]
    public class _Page_Auth_Views_ChangePassword_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
#line hidden

        public _Page_Auth_Views_ChangePassword_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {
WriteLiteral("<h2>");


Write(Resources.ChangePasswordAspx_ChangePassword);

WriteLiteral("</h2>\r\n<p>");


Write(Resources.ChangePasswordAspx_WriteActualPasswordAndNewOne);

WriteLiteral("</p>\r\n");


Write(Html.ValidationSummary());

WriteLiteral("\r\n");


 using (Html.BeginForm())
{

WriteLiteral("    <div id=\"changePassword\">\r\n        <table>\r\n            <tr>\r\n               " +
" <td class=\"label\">");


                             Write(Resources.ChangePasswordAspx_ActualPassword);

WriteLiteral(":\r\n                </td>\r\n                <td>\r\n                    ");


               Write(Html.Password(UserMapping.OldPasswordKey));

WriteLiteral("\r\n                    ");


               Write(Html.ValidationMessage(UserMapping.OldPasswordKey));

WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
" class=\"label\">");


                             Write(Resources.ChangePasswordAspx_NewPassword);

WriteLiteral(":\r\n                </td>\r\n                <td>\r\n                    ");


               Write(Html.Password(UserMapping.NewPasswordKey));

WriteLiteral("\r\n                    ");


               Write(Html.ValidationMessage(UserMapping.NewPasswordKey));

WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
" class=\"label\">");


                             Write(Resources.ChangePasswordAspx_ConfirmNewPassword);

WriteLiteral(":\r\n                </td>\r\n                <td>\r\n                    ");


               Write(Html.Password(UserMapping.NewPasswordBisKey));

WriteLiteral("\r\n                    ");


               Write(Html.ValidationMessage(UserMapping.NewPasswordBisKey));

WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
">\r\n                </td>\r\n                <td>\r\n                    <input type=" +
"\"submit\" value=\"");


                                           Write(Resources.ChangePasswordAspx_ChangePassword);

WriteLiteral("\" />\r\n                </td>\r\n            </tr>\r\n        </table>\r\n    </div>\r\n");


}
WriteLiteral(" ");


        }
    }
}
