#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signum.Web.Auth.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Signum.Entities;
    using Signum.Entities.Authorization;
    using Signum.Utilities;
    using Signum.Web;
    using Signum.Web.Auth;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Auth/Views/ResetPassword.cshtml")]
    public partial class ResetPassword : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ResetPassword()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Auth\Views\ResetPassword.cshtml"
  
    ViewBag.Title = AuthMessage.ResetPassword.NiceToString();

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">    $(function () { $(\"#email\").focus(); }); </script>\r\n<div");

WriteLiteral(" class=\"sf-reset-password-container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-sm-offset-4\"");

WriteLiteral(">\r\n        <h2>");

            
            #line 7 "..\..\Auth\Views\ResetPassword.cshtml"
       Write(AuthMessage.ResetPassword.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n        <p>");

            
            #line 8 "..\..\Auth\Views\ResetPassword.cshtml"
      Write(AuthMessage.ForgotYourPasswordEnterYourPasswordBelow.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n        <p>");

            
            #line 9 "..\..\Auth\Views\ResetPassword.cshtml"
      Write(AuthMessage.WeWillSendYouAnEmailWithALinkToResetYourPassword.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

WriteLiteral("        ");

            
            #line 10 "..\..\Auth\Views\ResetPassword.cshtml"
   Write(Html.ValudationSummaryStatic());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 12 "..\..\Auth\Views\ResetPassword.cshtml"
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Auth\Views\ResetPassword.cshtml"
     using (Html.BeginForm())
    {

            
            #line default
            #line hidden
WriteLiteral("        <br />\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"username\"");

WriteLiteral(" class=\"col-sm-offset-2 col-sm-2 control-label\"");

WriteLiteral(">");

            
            #line 17 "..\..\Auth\Views\ResetPassword.cshtml"
                                                                                Write(AuthMessage.Email.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 19 "..\..\Auth\Views\ResetPassword.cshtml"
               Write(Html.TextBox("email", null, new { @class = "form-control", placeholder = AuthMessage.Email.NiceToString() }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-offset-4 col-sm-6\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">");

            
            #line 24 "..\..\Auth\Views\ResetPassword.cshtml"
                                                             Write(AuthMessage.SendEmail.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

            
            #line 28 "..\..\Auth\Views\ResetPassword.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

        }
    }
}
#pragma warning restore 1591
