#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signum.Web.Extensions.Captcha.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Signum.Entities;
    using Signum.Utilities;
    using Signum.Web;
    
    #line 1 "..\..\Captcha\Views\captchaImage.cshtml"
    using Signum.Web.Captcha;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Captcha/Views/captchaImage.cshtml")]
    public class captchaImage : System.Web.Mvc.WebViewPage<dynamic>
    {
        public captchaImage()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Captcha\Views\captchaImage.cshtml"
Write(Html.CaptchaImage(50, 180, Request.Url.GetLeftPart(UriPartial.Authority), new Dictionary<string, object> { { "style", "float:left" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
