#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signum.Web.Extensions.Captcha.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Signum.Entities;
    using Signum.Utilities;
    using Signum.Web;
    
    #line 1 "..\..\Captcha\Views\captcha.cshtml"
    using Signum.Web.Captcha;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Captcha/Views/captcha.cshtml")]
    public class captcha : System.Web.Mvc.WebViewPage<dynamic>
    {
        public captcha()
        {
        }
        public override void Execute()
        {

WriteLiteral(@"<script type=""text/javascript"">
    function solicitarCaptcha() {
        $('#ajax-loader').show();
        $.ajax({
            url: ""Captcha.ashx/Refresh"",
            data: {},
            async: false,
            success:
                   function (msg) {
                       $(""#divCaptchaImage"").html(msg);
                       $('#ajax-loader').hide();
                   },
            error:
                   function (XMLHttpRequest, textStatus, errorThrown) {
                       $('#ajax-loader').hide();
                       ShowError(XMLHttpRequest, textStatus, errorThrown);
                   }
        });
    }

    function ShowError(XMLHttpRequest, textStatus, errorThrown) {
        var error = getErrorMessage(XMLHttpRequest.responseText);
        if (!error) {
            error = textStatus;
        }

        var message = error.length > 50 ? error.substring(0, 49) + ""..."" : error;
        SF.Notify.error(lang.signum.error + "": "" + message, 2000);

        SF.log(error);
        SF.log(XMLHttpRequest);
        SF.log(thrownError);

        alert(lang.signum.error + "": "" + error);

        SF.Blocker.disable();    
    }
</script>
<div id=""divCaptcha"">
    <label class=""sf-label-line"">
        Escriba estos caracteres:</label>
    <div id=""divCaptchaImage"">
");


            
            #line 44 "..\..\Captcha\Views\captcha.cshtml"
           Html.RenderPartial(CaptchaClient.CaptchaImageUrl);

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n    ");


            
            #line 46 "..\..\Captcha\Views\captcha.cshtml"
Write(Html.Href("solicitarNuevoCaptcha", "Solicite un nuevo código", "javascript:solicitarCaptcha();", "Solicite un nuevo código", null, new Dictionary<string, object> { { "style", "float:left" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"clearall\">\r\n    </div>\r\n    <label class=\"sf-label-line\" for=\"s" +
"fCaptcha\">\r\n        Aquí:</label>\r\n    ");


            
            #line 51 "..\..\Captcha\Views\captcha.cshtml"
Write(Html.TextBox("sfCaptcha", null, new { autocomplete = "off" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
