#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signum.Web.Extensions.Profiler.Views
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Profiler\Views\Times.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Signum.Entities;
    using Signum.Utilities;
    using Signum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Profiler/Views/Times.cshtml")]
    public class Times : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Times()
        {
        }
        public override void Execute()
        {

WriteLiteral(@"
<style type=""text/css"">
    .task
    {
        border-bottom: 1px solid #ddd;
    }
    .task .processName
    {
        font-size: 150%;
    }
    
    .task .numTimes
    {
        color: #666;
    }
    .task .max, .task .med, .task .min, .task .last
    {
        display: block;
        height: 10px;
        float: left;
        margin-right: 10px;
        margin-left: 0px;
    }
    
    .task .max
    {
        background: #b22222;
    }
    .task .med
    {
        background: #ff7722;
    }
    .task .min
    {
        background: #ffd700;
    }
    .task .last
    {
        background: #b27aff repeat-x;
    }
    .leftBorder
    {
        border-left: 1px solid #eee;
    }
    #tasks
    {
        width: 1200px;
    }
    
    #tasks .left
    {
        float: left;
    }    
    
    .sf-search-results .percentile0
    {
        background-color: #99CCFF;
    }
    .sf-search-results .percentile1
    {
        background-color: #fff;
    }
    .sf-search-results .percentile2
    {
        background-color: #FFCCCC;
    }
</style>

");


            
            #line 70 "..\..\Profiler\Views\Times.cshtml"
  
    ViewBag.Title = "Times";


            
            #line default
            #line hidden

            
            #line 73 "..\..\Profiler\Views\Times.cshtml"
Write(Html.ActionLink("Clear", "ClearTimes"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<ul id=\"tasks\">\r\n");


            
            #line 75 "..\..\Profiler\Views\Times.cshtml"
       
       int maxWitdh = 600;
       long maxValue = maxWitdh;
       if (TimeTracker.IdentifiedElapseds.Count > 0)
       {
           maxValue = TimeTracker.IdentifiedElapseds.OrderByDescending(p => p.Value.MaxTime).FirstEx().Value.MaxTime;
       }

       double ratio = 1;
       if (maxValue != 0) 
       { 
           ratio = maxWitdh / (double)maxValue;
       }
    

            
            #line default
            #line hidden

            
            #line 89 "..\..\Profiler\Views\Times.cshtml"
     foreach (KeyValuePair<string, TimeTrackerEntry> pair in TimeTracker.IdentifiedElapseds.OrderByDescending(p => p.Value.Average))
    {

            
            #line default
            #line hidden
WriteLiteral(@"        <li class=""task"">
            <table>
                <tr>
                    <td>
                        <table>
                            <tr>
                                <td width=""300"">
                                    <span class=""processName"">");


            
            #line 98 "..\..\Profiler\Views\Times.cshtml"
                                                         Write(pair.Key.Split(' ')[0]);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 99 "..\..\Profiler\Views\Times.cshtml"
                                     if (pair.Key.Split(' ').Length > 1)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <br />\r\n");



WriteLiteral("                                        <span class=\"entityName\">");


            
            #line 102 "..\..\Profiler\Views\Times.cshtml"
                                                            Write(pair.Key.Split(' ')[1]);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 103 "..\..\Profiler\Views\Times.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\r\n                            </tr>\r\n       " +
"                     <tr>\r\n                                <td>\r\n               " +
"                     <span class=\"numTimes\">Executed ");


            
            #line 108 "..\..\Profiler\Views\Times.cshtml"
                                                               Write(pair.Value.Count);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 108 "..\..\Profiler\Views\Times.cshtml"
                                                                                  Write(pair.Value.Count == 1 ? "time" : "times");

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                </td>\r\n                            </tr>" +
"\r\n                        </table>\r\n                    </td>\r\n                 " +
"   <td>\r\n                        <table>\r\n");


            
            #line 115 "..\..\Profiler\Views\Times.cshtml"
                             if (pair.Value.Count == 1)
                            {

            
            #line default
            #line hidden
WriteLiteral(@"                                <tr>
                                    <td width=""40"">
                                        Single:
                                    </td>
                                    <td class=""leftBorder"">
                                        <span class=""med"" style=""width:");


            
            #line 122 "..\..\Profiler\Views\Times.cshtml"
                                                                   Write((int)(pair.Value.Average * ratio));

            
            #line default
            #line hidden
WriteLiteral("px\"></span>");


            
            #line 122 "..\..\Profiler\Views\Times.cshtml"
                                                                                                                 Write(pair.Value.LastTime);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        ms (hace ");


            
            #line 123 "..\..\Profiler\Views\Times.cshtml"
                                             Write(new TimeSpan(DateTime.UtcNow.Subtract(pair.Value.LastDate).Ticks).ToShortString());

            
            #line default
            #line hidden
WriteLiteral(")\r\n                                    </td>\r\n                                </t" +
"r>\r\n");


            
            #line 126 "..\..\Profiler\Views\Times.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral(@"                                <tr>
                                    <td width=""40"">
                                        Max
                                    </td>
                                    <td class=""leftBorder"">
                                        <span class=""max"" style=""width:");


            
            #line 134 "..\..\Profiler\Views\Times.cshtml"
                                                                   Write((int)(pair.Value.MaxTime * ratio));

            
            #line default
            #line hidden
WriteLiteral("px\"></span>");


            
            #line 134 "..\..\Profiler\Views\Times.cshtml"
                                                                                                                 Write(pair.Value.MaxTime);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        ms (hace ");


            
            #line 135 "..\..\Profiler\Views\Times.cshtml"
                                             Write(new TimeSpan(DateTime.UtcNow.Subtract(pair.Value.MaxDate).Ticks).ToShortString());

            
            #line default
            #line hidden
WriteLiteral(")\r\n                                    </td>\r\n                                </t" +
"r>\r\n");



WriteLiteral(@"                                <tr>
                                    <td width=""40"">
                                        Average
                                    </td>
                                    <td class=""leftBorder"">
                                        <span class=""med"" style=""width:");


            
            #line 143 "..\..\Profiler\Views\Times.cshtml"
                                                                   Write((int)(pair.Value.Average * ratio));

            
            #line default
            #line hidden
WriteLiteral("px\"></span>");


            
            #line 143 "..\..\Profiler\Views\Times.cshtml"
                                                                                                                 Write(pair.Value.Average);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        ms\r\n                                   " +
" </td>\r\n                                </tr>\r\n");



WriteLiteral(@"                                <tr>
                                    <td width=""40"">
                                        Min
                                    </td>
                                    <td class=""leftBorder"">
                                        <span class=""min"" style=""width:");


            
            #line 152 "..\..\Profiler\Views\Times.cshtml"
                                                                   Write((int)(pair.Value.MinTime * ratio));

            
            #line default
            #line hidden
WriteLiteral("px\"></span>");


            
            #line 152 "..\..\Profiler\Views\Times.cshtml"
                                                                                                                 Write(pair.Value.MinTime);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        ms (hace ");


            
            #line 153 "..\..\Profiler\Views\Times.cshtml"
                                             Write(new TimeSpan(DateTime.UtcNow.Subtract(pair.Value.MinDate).Ticks).ToShortString());

            
            #line default
            #line hidden
WriteLiteral(")\r\n                                    </td>\r\n                                </t" +
"r>\r\n");



WriteLiteral(@"                                <tr>
                                    <td width=""40"">
                                        Last
                                    </td>
                                    <td class=""leftBorder"">
                                        <span class=""last"" style=""width:");


            
            #line 161 "..\..\Profiler\Views\Times.cshtml"
                                                                    Write((int)(pair.Value.LastTime * ratio));

            
            #line default
            #line hidden
WriteLiteral("px\"></span>");


            
            #line 161 "..\..\Profiler\Views\Times.cshtml"
                                                                                                                   Write(pair.Value.LastTime);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        ms (hace ");


            
            #line 162 "..\..\Profiler\Views\Times.cshtml"
                                             Write(new TimeSpan(DateTime.UtcNow.Subtract(pair.Value.LastDate).Ticks).ToShortString());

            
            #line default
            #line hidden
WriteLiteral(")\r\n                                    </td>\r\n                                </t" +
"r> \r\n");


            
            #line 165 "..\..\Profiler\Views\Times.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </table>\r\n                    </td>\r\n                </tr" +
">\r\n            </table>\r\n        </li>\r\n");


            
            #line 171 "..\..\Profiler\Views\Times.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n</asp:Content> ");


        }
    }
}
#pragma warning restore 1591
