/// <reference path="../Headers/es6-promises/es6-promises.d.ts"/>
/// <reference path="../Headers/jquery/jquery.d.ts"/>
/// <reference path="SF.ts"/>
/// <reference path="../Headers/bootstrap/bootstrap.d.ts"/>
/// <reference path="../Headers/bootstrap/bootstrap.datepicker.d.ts"/>
/// <reference path="../Headers/bootstrap/bootstrap.timepicker.d.ts"/>
/// <reference path="../Headers/bootstrap/typeahead.d.ts"/>
/// <reference path="SF.UI.ts"/>
//# sourceMappingURL=globals.js.map
