#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\UserQueries\Views\UserQuery.cshtml"
    using Signum.Engine;
    
    #line default
    #line hidden
    
    #line 3 "..\..\UserQueries\Views\UserQuery.cshtml"
    using Signum.Engine.Basics;
    
    #line default
    #line hidden
    
    #line 4 "..\..\UserQueries\Views\UserQuery.cshtml"
    using Signum.Engine.DynamicQuery;
    
    #line default
    #line hidden
    using Signum.Entities;
    
    #line 2 "..\..\UserQueries\Views\UserQuery.cshtml"
    using Signum.Entities.Basics;
    
    #line default
    #line hidden
    
    #line 9 "..\..\UserQueries\Views\UserQuery.cshtml"
    using Signum.Entities.DynamicQuery;
    
    #line default
    #line hidden
    
    #line 7 "..\..\UserQueries\Views\UserQuery.cshtml"
    using Signum.Entities.UserAssets;
    
    #line default
    #line hidden
    
    #line 6 "..\..\UserQueries\Views\UserQuery.cshtml"
    using Signum.Entities.UserQueries;
    
    #line default
    #line hidden
    using Signum.Utilities;
    using Signum.Web;
    
    #line 8 "..\..\UserQueries\Views\UserQuery.cshtml"
    using Signum.Web.UserAssets;
    
    #line default
    #line hidden
    
    #line 5 "..\..\UserQueries\Views\UserQuery.cshtml"
    using Signum.Web.UserQueries;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/UserQueries/Views/UserQuery.cshtml")]
    public partial class _UserQueries_Views_UserQuery_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _UserQueries_Views_UserQuery_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 12 "..\..\UserQueries\Views\UserQuery.cshtml"
 using (var e = Html.TypeContext<UserQueryEntity>())
{
    e.LabelColumns = new BsColumn(2);

    object queryName = QueryLogic.ToQueryName(e.Value.Query.Key);
    ViewData[ViewDataKeys.QueryDescription] = DynamicQueryManager.Current.QueryDescription(queryName); //To be use inside Repeaters
    
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\UserQueries\Views\UserQuery.cshtml"
Write(Html.EntityLine(e, f => f.Owner, el => el.Create = false));

            
            #line default
            #line hidden
            
            #line 19 "..\..\UserQueries\Views\UserQuery.cshtml"
                                                              
    
    using (var query = e.SubContext(f => f.Query))
    {
    
            
            #line default
            #line hidden
            
            #line 23 "..\..\UserQueries\Views\UserQuery.cshtml"
Write(Html.HiddenRuntimeInfo(query));

            
            #line default
            #line hidden
            
            #line 23 "..\..\UserQueries\Views\UserQuery.cshtml"
                                  
       
    
            
            #line default
            #line hidden
            
            #line 25 "..\..\UserQueries\Views\UserQuery.cshtml"
Write(Html.Hidden(query.Compose("Key"), query.Value.Key));

            
            #line default
            #line hidden
            
            #line 25 "..\..\UserQueries\Views\UserQuery.cshtml"
                                                       

    var niceName = QueryUtils.GetNiceName(query.Value.ToQueryName());

    
            
            #line default
            #line hidden
            
            #line 29 "..\..\UserQueries\Views\UserQuery.cshtml"
Write(Html.FormGroup(e, null, typeof(QueryEntity).NiceName(), Finder.IsFindable(queryName) ?
                     new HtmlTag("a").Class("form-control-static").Attr("href", Finder.FindRoute(queryName)).SetInnerText(niceName).ToHtml() :
                     Html.Span(null, niceName, "form-control-static")));

            
            #line default
            #line hidden
            
            #line 31 "..\..\UserQueries\Views\UserQuery.cshtml"
                                                                      

    }
    
    
            
            #line default
            #line hidden
            
            #line 35 "..\..\UserQueries\Views\UserQuery.cshtml"
Write(Html.ValueLine(e, f => f.DisplayName));

            
            #line default
            #line hidden
            
            #line 35 "..\..\UserQueries\Views\UserQuery.cshtml"
                                          
        
    var entityTypePrefix = e.SubContext(a => a.EntityType).Prefix;
        
    
            
            #line default
            #line hidden
            
            #line 39 "..\..\UserQueries\Views\UserQuery.cshtml"
Write(Html.EntityLine(e, f => f.EntityType, el =>
    {
        el.AutocompleteUrl = Url.Action("TypeAutocomplete", "Finder");
        el.AttachFunction = UserAssetsClient.Module["attachShowCurrentEntity"](el);
    }));

            
            #line default
            #line hidden
            
            #line 43 "..\..\UserQueries\Views\UserQuery.cshtml"
      
    

            
            #line default
            #line hidden
WriteLiteral("    <p");

WriteLiteral(" class=\"messageEntity col-sm-offset-2\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 46 "..\..\UserQueries\Views\UserQuery.cshtml"
   Write(UserQueryMessage.Use0ToFilterCurrentEntity.NiceToString().FormatWith(CurrentEntityConverter.CurrentEntityKey));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");

            
            #line 48 "..\..\UserQueries\Views\UserQuery.cshtml"

    
            
            #line default
            #line hidden
            
            #line 49 "..\..\UserQueries\Views\UserQuery.cshtml"
Write(Html.ValueLine(e, f => f.SearchOnLoad));

            
            #line default
            #line hidden
            
            #line 49 "..\..\UserQueries\Views\UserQuery.cshtml"
                                           
    
            
            #line default
            #line hidden
            
            #line 50 "..\..\UserQueries\Views\UserQuery.cshtml"
Write(Html.ValueLine(e, f => f.ShowFilterButton));

            
            #line default
            #line hidden
            
            #line 50 "..\..\UserQueries\Views\UserQuery.cshtml"
                                               
    
            
            #line default
            #line hidden
            
            #line 51 "..\..\UserQueries\Views\UserQuery.cshtml"
Write(Html.ValueLine(e, f => f.WithoutFilters));

            
            #line default
            #line hidden
            
            #line 51 "..\..\UserQueries\Views\UserQuery.cshtml"
                                             

    using (var sc = e.SubContext())
    {
        sc.FormGroupSize = FormGroupSize.Small;


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"repeater-inline form-inline sf-filters-list \"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 58 "..\..\UserQueries\Views\UserQuery.cshtml"
   Write(Html.EntityRepeater(e, f => f.Filters, er => { er.PreserveViewData = true; }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 60 "..\..\UserQueries\Views\UserQuery.cshtml"

    
            
            #line default
            #line hidden
            
            #line 61 "..\..\UserQueries\Views\UserQuery.cshtml"
Write(Html.ValueLine(e, f => f.ColumnsMode));

            
            #line default
            #line hidden
            
            #line 61 "..\..\UserQueries\Views\UserQuery.cshtml"
                                          

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"repeater-inline form-inline sf-filters-list\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 63 "..\..\UserQueries\Views\UserQuery.cshtml"
   Write(Html.EntityRepeater(e, f => f.Columns, er => { er.PreserveViewData = true; }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 65 "..\..\UserQueries\Views\UserQuery.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"repeater-inline form-inline sf-filters-list\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 67 "..\..\UserQueries\Views\UserQuery.cshtml"
   Write(Html.EntityRepeater(e, f => f.Orders, er => { er.PreserveViewData = true; }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 69 "..\..\UserQueries\Views\UserQuery.cshtml"
    }
    
    
            
            #line default
            #line hidden
            
            #line 71 "..\..\UserQueries\Views\UserQuery.cshtml"
Write(Html.ValueLine(e, f => f.PaginationMode));

            
            #line default
            #line hidden
            
            #line 71 "..\..\UserQueries\Views\UserQuery.cshtml"
                                             
    
            
            #line default
            #line hidden
            
            #line 72 "..\..\UserQueries\Views\UserQuery.cshtml"
Write(Html.ValueLine(e, f => f.ElementsPerPage));

            
            #line default
            #line hidden
            
            #line 72 "..\..\UserQueries\Views\UserQuery.cshtml"
                                              
}

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

        }
    }
}
#pragma warning restore 1591
