export default {
  text: {
    underline: "text-underline",
    code: "text-code",
  },
  code: "code-block",
  codeHighlight: {
    atrule: "code-token-attr",
    attr: "code-token-attr",
    boolean: "code-token-property",
    builtin: "code-token-selector",
    cdata: "code-token-comment",
    char: "code-token-selector",
    class: "code-token-function",
    "class-name": "code-token-function",
    comment: "code-token-comment",
    constant: "code-token-property",
    deleted: "code-token-property",
    doctype: "code-token-comment",
    entity: "code-token-operator",
    function: "code-token-function",
    important: "code-token-variable",
    inserted: "code-token-selector",
    keyword: "code-token-attr",
    namespace: "code-token-variable",
    number: "code-token-property",
    operator: "code-token-operator",
    prolog: "code-token-comment",
    property: "code-token-property",
    punctuation: "code-token-punctuation",
    regex: "code-token-variable",
    selector: "code-token-selector",
    string: "code-token-selector",
    symbol: "code-token-property",
    tag: "code-token-property",
    url: "code-token-operator",
    variable: "code-token-variable",
  },
};
