#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signum.Web.Extensions.SMS.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\SMS\Views\MultipleSMS.cshtml"
    using Signum.Engine;
    
    #line default
    #line hidden
    
    #line 2 "..\..\SMS\Views\MultipleSMS.cshtml"
    using Signum.Entities.SMS;
    
    #line default
    #line hidden
    
    #line 6 "..\..\SMS\Views\MultipleSMS.cshtml"
    using Signum.Utilities;
    
    #line default
    #line hidden
    
    #line 3 "..\..\SMS\Views\MultipleSMS.cshtml"
    using Signum.Web;
    
    #line default
    #line hidden
    
    #line 5 "..\..\SMS\Views\MultipleSMS.cshtml"
    using Signum.Web.Extensions.SMS.Models;
    
    #line default
    #line hidden
    
    #line 4 "..\..\SMS\Views\MultipleSMS.cshtml"
    using Signum.Web.SMS;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/SMS/Views/MultipleSMS.cshtml")]
    public partial class MultipleSMS : System.Web.Mvc.WebViewPage<dynamic>
    {
        public MultipleSMS()
        {
        }
        public override void Execute()
        {






WriteLiteral("\r\n");


            
            #line 8 "..\..\SMS\Views\MultipleSMS.cshtml"
Write(Html.RegisterUrls(new Dictionary<string, string> 
{ 
    { "getDictionaries", Url.Action<SMSController>(s => s.GetDictionaries()) },
    { "removeCharacters", Url.Action<SMSController>(s => s.RemoveNoSMSCharacters("")) }
}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 13 "..\..\SMS\Views\MultipleSMS.cshtml"
Write(Html.ScriptCss("~/SMS/Content/SF_SMS.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 15 "..\..\SMS\Views\MultipleSMS.cshtml"
 using (var e = Html.TypeContext<MultipleSMSModel>())
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"sf-sms-edit-container\">\r\n        ");


            
            #line 18 "..\..\SMS\Views\MultipleSMS.cshtml"
   Write(Html.ValueLine(e, s => s.Message, vl =>
        {
            vl.ValueLineType = ValueLineType.TextArea;
            vl.ValueHtmlProps["cols"] = "30";
            vl.ValueHtmlProps["rows"] = "6";
            vl.ValueHtmlProps["class"] = "sf-sms-msg-text";
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"sf-sms-characters-left\">\r\n            <p>\r\n                " +
"<span>");


            
            #line 27 "..\..\SMS\Views\MultipleSMS.cshtml"
                 Write(SmsMessage.RemainingCharacters.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("</span>: <span class=\"sf-sms-chars-left\"></span>\r\n            </p>\r\n        </div" +
">\r\n        <div>\r\n            <input type=\"button\" class=\"sf-button sf-sms-remov" +
"e-chars\" value=\"Remove non valid characters\" />\r\n        </div>\r\n    </div>\r\n");



WriteLiteral("    <br />\r\n");


            
            #line 35 "..\..\SMS\Views\MultipleSMS.cshtml"
    
            
            #line default
            #line hidden
            
            #line 35 "..\..\SMS\Views\MultipleSMS.cshtml"
Write(Html.ValueLine(e, s => s.From));

            
            #line default
            #line hidden
            
            #line 35 "..\..\SMS\Views\MultipleSMS.cshtml"
                                   
    
            
            #line default
            #line hidden
            
            #line 36 "..\..\SMS\Views\MultipleSMS.cshtml"
Write(Html.Hidden(e.Compose("ProviderKeys"), e.Value.ProviderKeys));

            
            #line default
            #line hidden
            
            #line 36 "..\..\SMS\Views\MultipleSMS.cshtml"
                                                                 ;
    
            
            #line default
            #line hidden
            
            #line 37 "..\..\SMS\Views\MultipleSMS.cshtml"
Write(Html.Hidden(e.Compose("WebTypeName"), e.Value.WebTypeName));

            
            #line default
            #line hidden
            
            #line 37 "..\..\SMS\Views\MultipleSMS.cshtml"
                                                               ;
}

            
            #line default
            #line hidden

            
            #line 39 "..\..\SMS\Views\MultipleSMS.cshtml"
Write(Html.ScriptsJs("~/SMS/Scripts/SF_SMS.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
