//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using Signum.Utilities;
    using Signum.Entities;
    using Signum.Web;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    using Signum.Web.Help;
    using Signum.Engine.WikiMarkup;
    using Signum.Web.Extensions;
    using Signum.Engine.Help;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Help/Views/ViewNamespace.cshtml")]
    public class _Page_Help_Views_ViewNamespace_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
#line hidden

        public _Page_Help_Views_ViewNamespace_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {





DefineSection("head", () => {

WriteLiteral("\r\n    ");


Write(Html.ScriptCss("~/help/Content/help.css"));

WriteLiteral("\r\n    ");


Write(Html.ScriptsJs("~/signum/Scripts/SF_Globals.js"));

WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


   
    Html.RenderPartial(HelpClient.Menu);
    NamespaceHelp nh = (NamespaceHelp)Model;
    ViewBag.Title = nh.Name;



 using (var f = Html.BeginForm("SaveNamespace", "Help", new { @namespace = nh.Name }, FormMethod.Post, new { id = "form-save" }))
{

WriteLiteral("    <div class=\"grid_12\" id=\"entityName\">\r\n        <h1>");


       Write(nh.Name);

WriteLiteral("</h1>\r\n        ");


   Write(Html.TextArea("description", nh.Description, 5, 80, new { @class = "editable" }));

WriteLiteral("\r\n        <span class=\"editor\" id=\"description-editor\">\r\n            ");


       Write(nh.Description.WikiParse(HelpClient.DefaultWikiSettings).Replace("\n", "<p>"));

WriteLiteral("\r\n        </span>\r\n    </div>\r\n");



WriteLiteral("    <div class=\"grid_4\">\r\n        <div class=\"sidebar\">\r\n            <h3>\r\n      " +
"          Temas relacionados</h3>\r\n            <ul>\r\n");


                   List<Type> types = (List<Type>)ViewData["nameSpace"];


                 foreach (Type t in types)
                {

WriteLiteral("                    <li><a href=\"");


                            Write(HelpLogic.EntityUrl(t));

WriteLiteral("\">");


                                                     Write(t.NiceName());

WriteLiteral("</a></li>\r\n");


                }

WriteLiteral("            </ul>\r\n        </div>\r\n    </div>\r\n");



WriteLiteral("    <div class=\"clear\">\r\n    </div>\r\n");


}
WriteLiteral(" ");


        }
    }
}
