#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signum.Web.Extensions.AuthAdmin.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Signum.Engine;
    
    #line 3 "..\..\AuthAdmin\Views\Types.cshtml"
    using Signum.Engine.Basics;
    
    #line default
    #line hidden
    using Signum.Entities;
    using Signum.Entities.Authorization;
    
    #line 2 "..\..\AuthAdmin\Views\Types.cshtml"
    using Signum.Entities.Basics;
    
    #line default
    #line hidden
    using Signum.Utilities;
    using Signum.Web;
    using Signum.Web.Auth;
    
    #line 1 "..\..\AuthAdmin\Views\Types.cshtml"
    using Signum.Web.AuthAdmin;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/AuthAdmin/Views/Types.cshtml")]
    public partial class Types : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Types()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\AuthAdmin\Views\Types.cshtml"
Write(Html.ScriptCss("~/authAdmin/Content/SF_AuthAdmin.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 5 "..\..\AuthAdmin\Views\Types.cshtml"
Write(Html.ScriptsJs("~/authAdmin/Scripts/SF_AuthAdmin.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(function () {
        SF.Auth.multiSelRadios($(document));
        SF.Auth.treeView();
        $("".sf-auth-rules .sf-submodule-trigger"").click(SF.Auth.openDialog);
        $(document).on(""click"", "".sf-auth-rules .sf-remove"", SF.Auth.removeCondition);
        $(document).on(""click"", "".sf-auth-rules .sf-create"", function (e) {
            e.preventDefault();
            SF.Auth.chooseConditionToAdd($(this), '");

            
            #line 14 "..\..\AuthAdmin\Views\Types.cshtml"
                                              Write(AuthMessage.AuthAdmin_ChooseACondition.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("\');\r\n        });\r\n    });\r\n</script>\r\n");

            
            #line 18 "..\..\AuthAdmin\Views\Types.cshtml"
  
    bool propertyRules = Navigator.Manager.EntitySettings.ContainsKey(typeof(PropertyRulePack));
    bool operationRules = Navigator.Manager.EntitySettings.ContainsKey(typeof(OperationRulePack));
    bool queryRules = Navigator.Manager.EntitySettings.ContainsKey(typeof(QueryRulePack));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 23 "..\..\AuthAdmin\Views\Types.cshtml"
 using (var tc = Html.TypeContext<TypeRulePack>())
{
    
            
            #line default
            #line hidden
            
            #line 25 "..\..\AuthAdmin\Views\Types.cshtml"
Write(Html.EntityLine(tc, f => f.Role));

            
            #line default
            #line hidden
            
            #line 25 "..\..\AuthAdmin\Views\Types.cshtml"
                                     
    
            
            #line default
            #line hidden
            
            #line 26 "..\..\AuthAdmin\Views\Types.cshtml"
Write(Html.ValueLine(tc, f => f.Strategy));

            
            #line default
            #line hidden
            
            #line 26 "..\..\AuthAdmin\Views\Types.cshtml"
                                        


            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"sf-auth-rules\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th>");

            
            #line 31 "..\..\AuthAdmin\Views\Types.cshtml"
               Write(typeof(TypeDN).NiceName());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>");

            
            #line 33 "..\..\AuthAdmin\Views\Types.cshtml"
               Write(TypeAllowed.Create.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>");

            
            #line 35 "..\..\AuthAdmin\Views\Types.cshtml"
               Write(TypeAllowed.Modify.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>");

            
            #line 37 "..\..\AuthAdmin\Views\Types.cshtml"
               Write(TypeAllowed.Read.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>");

            
            #line 39 "..\..\AuthAdmin\Views\Types.cshtml"
               Write(TypeAllowed.None.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>");

            
            #line 41 "..\..\AuthAdmin\Views\Types.cshtml"
               Write(AuthAdminMessage.Overriden.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n");

            
            #line 43 "..\..\AuthAdmin\Views\Types.cshtml"
                
            
            #line default
            #line hidden
            
            #line 43 "..\..\AuthAdmin\Views\Types.cshtml"
                 if (propertyRules)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <th>");

            
            #line 45 "..\..\AuthAdmin\Views\Types.cshtml"
                   Write(typeof(PropertyRouteDN).NiceName());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </th>\r\n");

            
            #line 47 "..\..\AuthAdmin\Views\Types.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 48 "..\..\AuthAdmin\Views\Types.cshtml"
                 if (operationRules)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <th>");

            
            #line 50 "..\..\AuthAdmin\Views\Types.cshtml"
                   Write(typeof(OperationDN).NiceName());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </th>\r\n");

            
            #line 52 "..\..\AuthAdmin\Views\Types.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 53 "..\..\AuthAdmin\Views\Types.cshtml"
                 if (queryRules)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <th>");

            
            #line 55 "..\..\AuthAdmin\Views\Types.cshtml"
                   Write(typeof(QueryDN).NiceName());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </th>\r\n");

            
            #line 57 "..\..\AuthAdmin\Views\Types.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n        </thead>\r\n");

            
            #line 60 "..\..\AuthAdmin\Views\Types.cshtml"
        
            
            #line default
            #line hidden
            
            #line 60 "..\..\AuthAdmin\Views\Types.cshtml"
         foreach (var iter in tc.TypeElementContext(p => p.Rules).GroupBy(a => a.Value.Resource.Namespace).OrderBy(a => a.Key).Iterate())
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td");

WriteLiteral(" colspan=\"6\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"sf-auth-namespace\"");

WriteLiteral("><span");

WriteAttribute("class", Tuple.Create(" class=\"", 2493), Tuple.Create("\"", 2575)
, Tuple.Create(Tuple.Create("", 2501), Tuple.Create("sf-auth-tree", 2501), true)
            
            #line 64 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create(" ", 2513), Tuple.Create<System.Object, System.Int32>(iter.IsLast ? "sf-auth-expanded-last" : "sf-auth-expanded"
            
            #line default
            #line hidden
, 2514), false)
);

WriteLiteral(">\r\n                    </span>\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2636), Tuple.Create("\"", 2690)
            
            #line 66 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create("", 2642), Tuple.Create<System.Object, System.Int32>(Url.Content("~/authAdmin/Images/namespace.png")
            
            #line default
            #line hidden
, 2642), false)
);

WriteLiteral(" />\r\n                        <span");

WriteLiteral(" class=\"sf-auth-namespace-name\"");

WriteLiteral(">");

            
            #line 67 "..\..\AuthAdmin\Views\Types.cshtml"
                                                        Write(iter.Value.Key);

            
            #line default
            #line hidden
WriteLiteral("</span> </a>\r\n                </td>\r\n            </tr>\r\n");

            
            #line 70 "..\..\AuthAdmin\Views\Types.cshtml"
            foreach (var iter2 in iter.Value.OrderBy(a => a.Value.Resource.CleanName).Iterate())
            {
                var item = iter2.Value;

            
            #line default
            #line hidden
WriteLiteral("            <tr");

WriteLiteral(" class=\"sf-auth-type\"");

WriteLiteral(" data-ns=\"");

            
            #line 73 "..\..\AuthAdmin\Views\Types.cshtml"
                                         Write(iter.Value.Key);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" ");

            
            #line 73 "..\..\AuthAdmin\Views\Types.cshtml"
                                                          Write(Html.Raw(item.Value.AvailableConditions.Any() ? ("data-type=\"" + item.Value.Resource.ClassName  + "\"") : ""));

            
            #line default
            #line hidden
WriteLiteral(">\r\n                <td>\r\n                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 3205), Tuple.Create("\"", 3275)
, Tuple.Create(Tuple.Create("", 3213), Tuple.Create("sf-auth-tree", 3213), true)
            
            #line 75 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create(" ", 3225), Tuple.Create<System.Object, System.Int32>(iter.IsLast ? "sf-auth-blank" : "sf-auth-line"
            
            #line default
            #line hidden
, 3226), false)
);

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 3331), Tuple.Create("\"", 3406)
, Tuple.Create(Tuple.Create("", 3339), Tuple.Create("sf-auth-tree", 3339), true)
            
            #line 77 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create(" ", 3351), Tuple.Create<System.Object, System.Int32>(iter2.IsLast ? "sf-auth-leaf-last" : "sf-auth-leaf"
            
            #line default
            #line hidden
, 3352), false)
);

WriteLiteral(">\r\n                    </div>\r\n");

            
            #line 79 "..\..\AuthAdmin\Views\Types.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 79 "..\..\AuthAdmin\Views\Types.cshtml"
                     if (!item.Value.AvailableConditions.IsNullOrEmpty())
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("title", Tuple.Create(" title=\"", 3562), Tuple.Create("\"", 3620)
            
            #line 81 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create("", 3570), Tuple.Create<System.Object, System.Int32>(AuthMessage.AuthAdmin_AddCondition.NiceToString()
            
            #line default
            #line hidden
, 3570), false)
);

WriteLiteral(" class=\"ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only sf" +
"-create sf-auth-condition-button\"");

WriteAttribute("style", Tuple.Create(" style=\"", 3735), Tuple.Create("\"", 3843)
            
            #line 81 "..\..\AuthAdmin\Views\Types.cshtml"
                                                                                                                                , Tuple.Create(Tuple.Create("", 3743), Tuple.Create<System.Object, System.Int32>(item.Value.Allowed.Conditions.Count == item.Value.AvailableConditions.Count ? "display:none" : ""
            
            #line default
            #line hidden
, 3743), false)
);

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"ui-button-icon-primary ui-icon ui-icon-circle-plus\"");

WriteLiteral("></span>\r\n                        </a>\r\n");

            
            #line 84 "..\..\AuthAdmin\Views\Types.cshtml"
                        

            
            #line default
            #line hidden
WriteLiteral("                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" class=\"sf-auth-available-conditions\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4106), Tuple.Create("\"", 4238)
            
            #line 85 "..\..\AuthAdmin\Views\Types.cshtml"
                             , Tuple.Create(Tuple.Create("", 4114), Tuple.Create<System.Object, System.Int32>(item.Value.AvailableConditions.ToString(ac => "{0}|{1}".Formato(TypeConditionNameDN.UniqueKey(ac), ac.NiceToString()), ",")
            
            #line default
            #line hidden
, 4114), false)
);

WriteLiteral(" />\r\n");

            
            #line 86 "..\..\AuthAdmin\Views\Types.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"sf-auth-label\"");

WriteLiteral(">");

            
            #line 87 "..\..\AuthAdmin\Views\Types.cshtml"
                                           Write(item.Value.Resource.ToType().NiceName());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

WriteLiteral("                    ");

            
            #line 88 "..\..\AuthAdmin\Views\Types.cshtml"
               Write(Html.HiddenRuntimeInfo(item, i => i.Resource));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 89 "..\..\AuthAdmin\Views\Types.cshtml"
               Write(Html.Hidden(item.Compose("AllowedBase"), item.Value.AllowedBase.Fallback.ToStringParts() + (item.Value.AllowedBase.Conditions.IsEmpty() ? "" : (";" + item.Value.AllowedBase.Conditions.ToString(a => "{0}-{1}".Formato(TypeConditionNameDN.UniqueKey(a.ConditionName), a.Allowed.ToStringParts()), ";")))));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n");

            
            #line 91 "..\..\AuthAdmin\Views\Types.cshtml"
                
            
            #line default
            #line hidden
            
            #line 91 "..\..\AuthAdmin\Views\Types.cshtml"
                 using (var fallback = item.SubContext(a => a.Allowed.Fallback))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td>\r\n                        <a");

WriteLiteral(" class=\"sf-auth-chooser sf-auth-create\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 95 "..\..\AuthAdmin\Views\Types.cshtml"
                       Write(Html.CheckBox(fallback.Compose("Create"), fallback.Value.IsActive(TypeAllowedBasic.Create), new Dictionary<string, object> { { "data-tag", "Create" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </td>\r\n");

WriteLiteral("                    <td>\r\n                        <a");

WriteLiteral(" class=\"sf-auth-chooser sf-auth-modify\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 100 "..\..\AuthAdmin\Views\Types.cshtml"
                       Write(Html.CheckBox(fallback.Compose("Modify"), fallback.Value.IsActive(TypeAllowedBasic.Modify), new Dictionary<string, object> { { "data-tag", "Modify" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </td>\r\n");

WriteLiteral("                    <td>\r\n                        <a");

WriteLiteral(" class=\"sf-auth-chooser sf-auth-read\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 105 "..\..\AuthAdmin\Views\Types.cshtml"
                       Write(Html.CheckBox(fallback.Compose("Read"), fallback.Value.IsActive(TypeAllowedBasic.Read), new Dictionary<string, object> { { "data-tag", "Read" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </td>\r\n");

WriteLiteral("                    <td>\r\n                        <a");

WriteLiteral(" class=\"sf-auth-chooser sf-auth-none\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 110 "..\..\AuthAdmin\Views\Types.cshtml"
                       Write(Html.CheckBox(fallback.Compose("None"), fallback.Value.IsActive(TypeAllowedBasic.None), new Dictionary<string, object> { { "data-tag", "None" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </td>\r\n");

            
            #line 113 "..\..\AuthAdmin\Views\Types.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"sf-auth-type-only\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 115 "..\..\AuthAdmin\Views\Types.cshtml"
               Write(Html.CheckBox(item.Compose("Overriden"), item.Value.Overriden, new { disabled = "disabled", @class = "sf-auth-overriden" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n");

            
            #line 117 "..\..\AuthAdmin\Views\Types.cshtml"
                
            
            #line default
            #line hidden
            
            #line 117 "..\..\AuthAdmin\Views\Types.cshtml"
                 if (propertyRules)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"sf-auth-type-only\"");

WriteLiteral(">\r\n");

            
            #line 120 "..\..\AuthAdmin\Views\Types.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 120 "..\..\AuthAdmin\Views\Types.cshtml"
                         if (item.Value.Properties.HasValue)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"sf-auth-property\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"sf-submodule-trigger\"");

WriteAttribute("href", Tuple.Create(" href=\"", 6754), Tuple.Create("\"", 6864)
            
            #line 123 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create("", 6761), Tuple.Create<System.Object, System.Int32>(Url.Action((AuthAdminController a) => a.Properties(tc.Value.Role, item.Value.Resource.ToLite(), null))
            
            #line default
            #line hidden
, 6761), false)
);

WriteLiteral(">\r\n                                    <span");

WriteAttribute("class", Tuple.Create(" class=\"", 6909), Tuple.Create("\"", 6982)
, Tuple.Create(Tuple.Create("", 6917), Tuple.Create("sf-auth-thumb", 6917), true)
, Tuple.Create(Tuple.Create(" ", 6930), Tuple.Create("sf-auth-", 6931), true)
            
            #line 124 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create("", 6939), Tuple.Create<System.Object, System.Int32>(item.Value.Properties.ToString().ToLower()
            
            #line default
            #line hidden
, 6939), false)
);

WriteLiteral(">\r\n                                    </span></a>\r\n                            <" +
"/div>\r\n");

            
            #line 127 "..\..\AuthAdmin\Views\Types.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n");

            
            #line 129 "..\..\AuthAdmin\Views\Types.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 130 "..\..\AuthAdmin\Views\Types.cshtml"
                 if (operationRules)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"sf-auth-type-only\"");

WriteLiteral(">\r\n");

            
            #line 133 "..\..\AuthAdmin\Views\Types.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 133 "..\..\AuthAdmin\Views\Types.cshtml"
                         if (item.Value.Operations.HasValue)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"sf-auth-operation\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"sf-submodule-trigger\"");

WriteAttribute("href", Tuple.Create(" href=\"", 7466), Tuple.Create("\"", 7576)
            
            #line 136 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create("", 7473), Tuple.Create<System.Object, System.Int32>(Url.Action((AuthAdminController a) => a.Operations(tc.Value.Role, item.Value.Resource.ToLite(), null))
            
            #line default
            #line hidden
, 7473), false)
);

WriteLiteral(">\r\n                                    <span");

WriteAttribute("class", Tuple.Create(" class=\"", 7621), Tuple.Create("\"", 7694)
, Tuple.Create(Tuple.Create("", 7629), Tuple.Create("sf-auth-thumb", 7629), true)
, Tuple.Create(Tuple.Create(" ", 7642), Tuple.Create("sf-auth-", 7643), true)
            
            #line 137 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create("", 7651), Tuple.Create<System.Object, System.Int32>(item.Value.Operations.ToString().ToLower()
            
            #line default
            #line hidden
, 7651), false)
);

WriteLiteral(">\r\n                                    </span></a>\r\n                            <" +
"/div>\r\n");

            
            #line 140 "..\..\AuthAdmin\Views\Types.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n");

            
            #line 142 "..\..\AuthAdmin\Views\Types.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 143 "..\..\AuthAdmin\Views\Types.cshtml"
                 if (queryRules)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"sf-auth-type-only\"");

WriteLiteral(">\r\n");

            
            #line 146 "..\..\AuthAdmin\Views\Types.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 146 "..\..\AuthAdmin\Views\Types.cshtml"
                         if (item.Value.Queries.HasValue)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"sf-auth-query\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"sf-submodule-trigger\"");

WriteAttribute("href", Tuple.Create(" href=\"", 8167), Tuple.Create("\"", 8274)
            
            #line 149 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create("", 8174), Tuple.Create<System.Object, System.Int32>(Url.Action((AuthAdminController a) => a.Queries(tc.Value.Role, item.Value.Resource.ToLite(), null))
            
            #line default
            #line hidden
, 8174), false)
);

WriteLiteral(">\r\n                                    <span");

WriteAttribute("class", Tuple.Create(" class=\"", 8319), Tuple.Create("\"", 8389)
, Tuple.Create(Tuple.Create("", 8327), Tuple.Create("sf-auth-thumb", 8327), true)
, Tuple.Create(Tuple.Create(" ", 8340), Tuple.Create("sf-auth-", 8341), true)
            
            #line 150 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create("", 8349), Tuple.Create<System.Object, System.Int32>(item.Value.Queries.ToString().ToLower()
            
            #line default
            #line hidden
, 8349), false)
);

WriteLiteral("></span>\r\n                                </a>\r\n                            </div" +
">\r\n");

            
            #line 153 "..\..\AuthAdmin\Views\Types.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n");

            
            #line 155 "..\..\AuthAdmin\Views\Types.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 157 "..\..\AuthAdmin\Views\Types.cshtml"
                    var conditions = item.Compose("Allowed", "Conditions"); 
                
                    foreach (var conditionIter in item.Value.Allowed.Conditions.Select((c, i) => new { Condition = c, Index = i, ControlId =  TypeContextUtilities.Compose(conditions, i.ToString())}).Iterate())
                    {
                        var condition = conditionIter.Value.Condition;
                        var controlId = conditionIter.Value.ControlId;
                        

            
            #line default
            #line hidden
WriteLiteral("            <tr");

WriteLiteral(" class=\"sf-auth-condition\"");

WriteLiteral(" data-ns=\"");

            
            #line 164 "..\..\AuthAdmin\Views\Types.cshtml"
                                              Write(iter.Value.Key);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-type=\"");

            
            #line 164 "..\..\AuthAdmin\Views\Types.cshtml"
                                                                          Write(item.Value.Resource.ClassName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-condition=\"");

            
            #line 164 "..\..\AuthAdmin\Views\Types.cshtml"
                                                                                                                          Write(TypeConditionNameDN.UniqueKey(condition.ConditionName));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-index=\"");

            
            #line 164 "..\..\AuthAdmin\Views\Types.cshtml"
                                                                                                                                                                                               Write(conditionIter.Value.Index);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                <td>\r\n                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 9338), Tuple.Create("\"", 9408)
, Tuple.Create(Tuple.Create("", 9346), Tuple.Create("sf-auth-tree", 9346), true)
            
            #line 166 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create(" ", 9358), Tuple.Create<System.Object, System.Int32>(iter.IsLast ? "sf-auth-blank" : "sf-auth-line"
            
            #line default
            #line hidden
, 9359), false)
);

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 9464), Tuple.Create("\"", 9535)
, Tuple.Create(Tuple.Create("", 9472), Tuple.Create("sf-auth-tree", 9472), true)
            
            #line 168 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create(" ", 9484), Tuple.Create<System.Object, System.Int32>(iter2.IsLast ? "sf-auth-blank" : "sf-auth-line"
            
            #line default
            #line hidden
, 9485), false)
);

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 9591), Tuple.Create("\"", 9674)
, Tuple.Create(Tuple.Create("", 9599), Tuple.Create("sf-auth-tree", 9599), true)
            
            #line 170 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create(" ", 9611), Tuple.Create<System.Object, System.Int32>(conditionIter.IsLast ? "sf-auth-leaf-last" : "sf-auth-leaf"
            
            #line default
            #line hidden
, 9612), false)
);

WriteLiteral(">\r\n                    </div>\r\n                    <a");

WriteLiteral(" class=\"ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only sf" +
"-remove sf-auth-condition-button\"");

WriteAttribute("title", Tuple.Create(" title=\"", 9842), Tuple.Create("\"", 9905)
            
            #line 172 "..\..\AuthAdmin\Views\Types.cshtml"
                                                                 , Tuple.Create(Tuple.Create("", 9850), Tuple.Create<System.Object, System.Int32>(AuthMessage.AuthAdmin_RemoveCondition.NiceToString()
            
            #line default
            #line hidden
, 9850), false)
);

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"ui-button-icon-primary ui-icon ui-icon-circle-close\"");

WriteLiteral("></span>\r\n                    </a>\r\n                    <span");

WriteLiteral(" class=\"sf-auth-label\"");

WriteLiteral(">");

            
            #line 175 "..\..\AuthAdmin\Views\Types.cshtml"
                                           Write(condition.ConditionName.NiceToString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

WriteLiteral("                    ");

            
            #line 176 "..\..\AuthAdmin\Views\Types.cshtml"
               Write(Html.Hidden(TypeContextUtilities.Compose(controlId, "ConditionName"), TypeConditionNameDN.UniqueKey(condition.ConditionName)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                \r\n");

            
            #line 179 "..\..\AuthAdmin\Views\Types.cshtml"
                
            
            #line default
            #line hidden
            
            #line 179 "..\..\AuthAdmin\Views\Types.cshtml"
                  var allowed = TypeContextUtilities.Compose(controlId, "Allowed");
            
            #line default
            #line hidden
WriteLiteral("\r\n                \r\n                    <td>\r\n                        <a");

WriteLiteral(" class=\"sf-auth-chooser sf-auth-create\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 183 "..\..\AuthAdmin\Views\Types.cshtml"
                       Write(Html.CheckBox(TypeContextUtilities.Compose(allowed, "Create"), condition.Allowed.IsActive(TypeAllowedBasic.Create), new Dictionary<string, object> { { "data-tag", "Create" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </td>\r\n                    <t" +
"d>\r\n                        <a");

WriteLiteral(" class=\"sf-auth-chooser sf-auth-modify\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 188 "..\..\AuthAdmin\Views\Types.cshtml"
                       Write(Html.CheckBox(TypeContextUtilities.Compose(allowed, "Modify"), condition.Allowed.IsActive(TypeAllowedBasic.Modify), new Dictionary<string, object> { { "data-tag", "Modify" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </td>\r\n                    <t" +
"d>\r\n                        <a");

WriteLiteral(" class=\"sf-auth-chooser sf-auth-read\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 193 "..\..\AuthAdmin\Views\Types.cshtml"
                       Write(Html.CheckBox(TypeContextUtilities.Compose(allowed, "Read"), condition.Allowed.IsActive(TypeAllowedBasic.Read), new Dictionary<string, object> { { "data-tag", "Read" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </td>\r\n                    <t" +
"d>\r\n                        <a");

WriteLiteral(" class=\"sf-auth-chooser sf-auth-none\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 198 "..\..\AuthAdmin\Views\Types.cshtml"
                       Write(Html.CheckBox(TypeContextUtilities.Compose(allowed, "None"), condition.Allowed.IsActive(TypeAllowedBasic.None), new Dictionary<string, object> { { "data-tag", "None" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </td>\r\n                \r\n    " +
"            <td");

WriteAttribute("colspan", Tuple.Create(" colspan=\"", 11876), Tuple.Create("\"", 11966)
            
            #line 202 "..\..\AuthAdmin\Views\Types.cshtml"
, Tuple.Create(Tuple.Create("", 11886), Tuple.Create<System.Object, System.Int32>(1 + (propertyRules ? 1 : 0) + (operationRules ? 1 : 0) + (queryRules ? 1 : 0)
            
            #line default
            #line hidden
, 11886), false)
);

WriteLiteral(">\r\n                </td>\r\n            </tr>\r\n");

            
            #line 205 "..\..\AuthAdmin\Views\Types.cshtml"
                    }
                
            }
        }

            
            #line default
            #line hidden
WriteLiteral("    </table>\r\n");

            
            #line 210 "..\..\AuthAdmin\Views\Types.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
