#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signum.Web.Chart.Views
{
    using System;
    using System.Collections.Generic;
    
    #line 4 "..\..\Chart\Views\ChartPalette.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 10 "..\..\Chart\Views\ChartPalette.cshtml"
    using Signum.Engine;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Chart\Views\ChartPalette.cshtml"
    using Signum.Engine.DynamicQuery;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Chart\Views\ChartPalette.cshtml"
    using Signum.Entities;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Chart\Views\ChartPalette.cshtml"
    using Signum.Entities.Chart;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Chart\Views\ChartPalette.cshtml"
    using Signum.Entities.DynamicQuery;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Chart\Views\ChartPalette.cshtml"
    using Signum.Entities.Reflection;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Chart\Views\ChartPalette.cshtml"
    using Signum.Utilities;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Chart\Views\ChartPalette.cshtml"
    using Signum.Web;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Chart\Views\ChartPalette.cshtml"
    using Signum.Web.Chart;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Chart/Views/ChartPalette.cshtml")]
    public partial class ChartPalette : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ChartPalette()
        {
        }
        public override void Execute()
        {
            
            #line 11 "..\..\Chart\Views\ChartPalette.cshtml"
Write(Html.ScriptCss("~/Chart/Content/Chart.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 13 "..\..\Chart\Views\ChartPalette.cshtml"
 using (var cpt = Html.TypeContext<ChartPaletteModel>())
{
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Chart\Views\ChartPalette.cshtml"
Write(Html.HiddenRuntimeInfo(cpt, cp => cp.Type));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Chart\Views\ChartPalette.cshtml"
                                               

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"table form-vertical\"");

WriteLiteral(" style=\"width:auto\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th>Color\r\n                " +
"</th>\r\n                <th>Id\r\n                </th>\r\n                <th>Text\r\n" +
"                </th>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r\n");

            
            #line 28 "..\..\Chart\Views\ChartPalette.cshtml"
            
            
            #line default
            #line hidden
            
            #line 28 "..\..\Chart\Views\ChartPalette.cshtml"
             foreach (TypeContext<ChartColorEntity> clc in cpt.TypeElementContext(cp => cp.Colors))
            {  

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 32 "..\..\Chart\Views\ChartPalette.cshtml"
                   Write(Html.HiddenRuntimeInfo(clc, cl => cl.Related));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 33 "..\..\Chart\Views\ChartPalette.cshtml"
                   Write(Html.ValueLine(clc, c=>c.Color, vl=> vl.FormGroupStyle = FormGroupStyle.SrOnly));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Chart\Views\ChartPalette.cshtml"
                   Write(clc.Value.Related.Id);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 39 "..\..\Chart\Views\ChartPalette.cshtml"
                   Write(clc.Value.Related.ToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n");

            
            #line 42 "..\..\Chart\Views\ChartPalette.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n");

            
            #line 45 "..\..\Chart\Views\ChartPalette.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
