#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Chart\Views\ChartScript.cshtml"
    using Signum.Engine;
    
    #line default
    #line hidden
    using Signum.Entities;
    
    #line 1 "..\..\Chart\Views\ChartScript.cshtml"
    using Signum.Entities.Chart;
    
    #line default
    #line hidden
    using Signum.Utilities;
    using Signum.Web;
    
    #line 4 "..\..\Chart\Views\ChartScript.cshtml"
    using Signum.Web.Chart;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Chart\Views\ChartScript.cshtml"
    using Signum.Web.Files;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Chart/Views/ChartScript.cshtml")]
    public partial class _Chart_Views_ChartScript_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Chart_Views_ChartScript_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Chart\Views\ChartScript.cshtml"
Write(Html.ScriptCss(
    "~/Chart/Content/Chart.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Chart\Views\ChartScript.cshtml"
 using (var cc = Html.TypeContext<ChartScriptEntity>())
{
    var imageRoute = cc.Compose("ImageIco");
    
   

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-11\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 14 "..\..\Chart\Views\ChartScript.cshtml"
       Write(Html.ValueLine(cc, c => c.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Chart\Views\ChartScript.cshtml"
       Write(Html.FileLine(cc, c => c.Icon.Try(i => i.Retrieve()), fl =>
    {
        fl.LabelText = Html.PropertyNiceName(() => cc.Value.Icon);
        fl.AttachFunction = ChartClient.ModuleScript["refreshIcon"](fl, imageRoute);
    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 20 "..\..\Chart\Views\ChartScript.cshtml"
       Write(Html.ValueLine(cc, c => c.GroupBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">\r\n");

            
            #line 23 "..\..\Chart\Views\ChartScript.cshtml"
            
            
            #line default
            #line hidden
            
            #line 23 "..\..\Chart\Views\ChartScript.cshtml"
             if (cc.Value.Icon != null && !cc.Value.Icon.IsNew)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                    <img");

WriteAttribute("id", Tuple.Create(" id=\"", 857), Tuple.Create("\"", 873)
            
            #line 26 "..\..\Chart\Views\ChartScript.cshtml"
, Tuple.Create(Tuple.Create("", 862), Tuple.Create<System.Object, System.Int32>(imageRoute
            
            #line default
            #line hidden
, 862), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 874), Tuple.Create("\"", 970)
            
            #line 26 "..\..\Chart\Views\ChartScript.cshtml"
, Tuple.Create(Tuple.Create("", 880), Tuple.Create<System.Object, System.Int32>(Url.Action((FileController fc) => fc.Download(new RuntimeInfo(cc.Value.Icon).ToString()))
            
            #line default
            #line hidden
, 880), false)
);

WriteLiteral(" />\r\n                </div>\r\n");

            
            #line 28 "..\..\Chart\Views\ChartScript.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n");

            
            #line 31 "..\..\Chart\Views\ChartScript.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"sf-chartscript-columns\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 33 "..\..\Chart\Views\ChartScript.cshtml"
   Write(Html.EntityRepeater(cc, c => c.Columns));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 35 "..\..\Chart\Views\ChartScript.cshtml"
    
            
            #line default
            #line hidden
            
            #line 35 "..\..\Chart\Views\ChartScript.cshtml"
Write(Html.EntityRepeater(cc, c => c.Parameters));

            
            #line default
            #line hidden
            
            #line 35 "..\..\Chart\Views\ChartScript.cshtml"
                                               
    
            
            #line default
            #line hidden
            
            #line 36 "..\..\Chart\Views\ChartScript.cshtml"
Write(Html.Partial(Signum.Web.Chart.ChartClient.ChartScriptCodeView, cc));

            
            #line default
            #line hidden
            
            #line 36 "..\..\Chart\Views\ChartScript.cshtml"
                                                                       
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
